### PR TITLE
Add bower.json to publish repo to bower

### PR DESCRIPTION
**Pull request by indrasantosa**
Hi,
Im adding bower.json to help to publish the repo to bower.
Im a bower user, so I find it really helpful to have this repo up to bower.
Cheers!

### CODE REVIEW

**Comment by gabipurcaru** [comment]
Hi @indrasantosa,

Sorry for the (very) late reply -- this looks good. I noticed that you've registered the package from your fork. Can you unregister it (https://github.com/bower/bower/issues/120) and let me register it from `cinely/mule-uploader`, as this is the main repo?

Cheers,
Gabi

**Comment by indrasantosa** [comment]
Hey @gabipurcaru,

No problem. Thanks for replying and Impressive work I'm very happy with this library. And I have unregistered it from the bower repository, you can register it now.

Cheers,
Indra

**Comment by gabipurcaru** [comment]
It doesn't seem to work -- https://asciinema.org/a/5iwnuz4vkpclfc460oy8aaf0v

**Comment by indrasantosa** [comment]
Hi @gabipurcaru, can you try again? I have tried to delete again, it should be OK for now.

**Comment by gabipurcaru** [comment]
Awesome, @indrasantosa! Thank you very much!

```
$ bower info mule-uploader                                                                                                                            bower mule-uploader#*       not-cached https://github.com/cinely/mule-uploader.git#*
bower mule-uploader#*          resolve https://github.com/cinely/mule-uploader.git#*
bower mule-uploader#*         checkout v1.0.0
bower mule-uploader#*         resolved https://github.com/cinely/mule-uploader.git#1.0.0

{
  name: 'mule-uploader',
  main: 'mule-uploader.js',
  version: '1.0.0',
  homepage: 'https://github.com/cinely/mule-uploader',
  authors: [
    'gabipurcaru'
  ],
  description: 'Subborn HTML5 File Uploader for Amazon S3',
  moduleType: [
    'globals'
  ],
  keywords: [
    'uploader',
    'mule-uploader',
    'S3',
    'uploader',
    'Amazon',
    'S3'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'components',
    'test',
    'tests'
  ]
}

Available versions:
  - 1.0.0

You can request info for a specific version with 'bower info mule-uploader#<version>'

```

**Pull request merged**
